spring:
  application:
    name: galchat
  ai:
    deepseek:
      base-url: https://api.deepseek.com
      api-key: sk-c267b8feed9b4b72ba27c64f4db855af
      chat:
        options:
          model: deepseek-v4-flash
          temperature: 1.0
    model:
      embedding: ollama
    ollama:
        embedding:
          options:
            model: qwen3-embedding:latest
            dimensions: 1024
  cache:
    type: redis
    # 不配置 cache-names 或留空，则任何 @Cacheable 新名称都会自动创建
    redis:
      time-to-live: 60m
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: wyyd
    password:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
logging:
  level:
    com.me.galchat:
      mapper: debug
      service: info
      controller: info
    org.springframework.ai.chat.client.advisor: debug
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
galchat:
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucket-name: galchat
    region: cn-beijing
  aliemail:
    account-name: usercheck@galchat.top
    reply-to-address: false