spring:
  application:
    name: galchat
  ai:
    deepseek:
      base-url: ${SPRING_AI_DEEPSEEK_BASE_URL:https://api.deepseek.com}
      api-key: ${SPRING_AI_DEEPSEEK_API_KEY:}
      chat:
        options:
          model: ${SPRING_AI_DEEPSEEK_CHAT_OPTIONS_MODEL:deepseek-v4-flash}
          temperature: ${SPRING_AI_DEEPSEEK_CHAT_OPTIONS_TEMPERATURE:1.0}
    model:
      embedding: ollama
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}
      embedding:
        options:
          model: ${SPRING_AI_OLLAMA_EMBEDDING_OPTIONS_MODEL:qwen3-embedding:latest}
          dimensions: ${SPRING_AI_OLLAMA_EMBEDDING_OPTIONS_DIMENSIONS:1024}
  cache:
    type: redis
    # 不配置 cache-names 或留空，则任何 @Cacheable 新名称都会自动创建
    redis:
      time-to-live: 60m
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:wyyd}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      database: ${SPRING_DATA_REDIS_DATABASE:0}
logging:
  level:
    com.me.galchat:
      mapper: debug
      service: info
      controller: info
    org.springframework.ai.chat.client.advisor: debug
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
galchat:
  service:
    bert-url: ${GALCHAT_BERT_URL:http://localhost:8081}
    reranker-url: ${GALCHAT_RERANKER_URL:http://localhost:8082}
  alioss:
    endpoint: ${GALCHAT_ALIOSS_ENDPOINT:https://oss-cn-beijing.aliyuncs.com}
    bucket-name: ${GALCHAT_ALIOSS_BUCKET_NAME:galchat}
    region: ${GALCHAT_ALIOSS_REGION:cn-beijing}
