package com.me.galchat.domain.vo;

import java.util.Map;

public record CocDiceCharacterVO(
        Long cardId,
        String actorType,
        Long participantId,
        String name,
        Map<String, Integer> checkValues,
        Integer hpCurrent,
        Integer hpMax,
        Integer sanCurrent,
        Integer sanMax,
        Integer con,
        Integer build,
        Integer armor,
        Boolean majorWound,
        Boolean unconscious,
        Boolean dying,
        Boolean dead,
        Boolean temporaryInsanity,
        String temporaryInsanityPhase,
        Integer temporaryInsanityRemainingHours,
        Boolean inCover,
        Boolean coverActionForfeitPending,
        Integer stunnedRemainingRounds,
        Long restrainedByCharacterId,
        String restrainedByCharacterName,
        Boolean meleeAttackedThisRound) {

    public CocDiceCharacterVO(
            Long cardId,
            String actorType,
            Long participantId,
            String name,
            Map<String, Integer> checkValues,
            Integer hpCurrent,
            Integer hpMax,
            Integer sanCurrent,
            Integer sanMax,
            Integer con,
            Integer armor,
            Boolean majorWound,
            Boolean unconscious,
            Boolean dying,
            Boolean dead,
            Boolean temporaryInsanity,
            String temporaryInsanityPhase,
            Integer temporaryInsanityRemainingHours) {
        this(cardId, actorType, participantId, name, checkValues,
                hpCurrent, hpMax, sanCurrent, sanMax, con, null, armor,
                majorWound, unconscious, dying, dead,
                temporaryInsanity, temporaryInsanityPhase,
                temporaryInsanityRemainingHours,
                false, false, 0, null, null, false);
    }

    public CocDiceCharacterVO(
            Long cardId,
            String actorType,
            Long participantId,
            String name,
            Map<String, Integer> checkValues,
            Integer hpCurrent,
            Integer hpMax,
            Integer sanCurrent,
            Integer sanMax,
            Integer con,
            Integer armor,
            Boolean majorWound,
            Boolean unconscious,
            Boolean dying,
            Boolean dead,
            Boolean temporaryInsanity,
            String temporaryInsanityPhase,
            Integer temporaryInsanityRemainingHours,
            Boolean inCover,
            Boolean coverActionForfeitPending,
            Integer stunnedRemainingRounds,
            Long restrainedByCharacterId,
            Boolean meleeAttackedThisRound) {
        this(cardId, actorType, participantId, name, checkValues,
                hpCurrent, hpMax, sanCurrent, sanMax, con, null, armor,
                majorWound, unconscious, dying, dead,
                temporaryInsanity, temporaryInsanityPhase,
                temporaryInsanityRemainingHours,
                inCover, coverActionForfeitPending,
                stunnedRemainingRounds, restrainedByCharacterId, null,
                meleeAttackedThisRound);
    }

    public CocDiceCharacterVO(
            Long cardId,
            String actorType,
            Long participantId,
            String name,
            Map<String, Integer> checkValues,
            Integer hpCurrent,
            Integer hpMax,
            Integer sanCurrent,
            Integer sanMax,
            Integer con,
            Integer build,
            Integer armor,
            Boolean majorWound,
            Boolean unconscious,
            Boolean dying,
            Boolean dead,
            Boolean temporaryInsanity,
            String temporaryInsanityPhase,
            Integer temporaryInsanityRemainingHours,
            Boolean inCover,
            Boolean coverActionForfeitPending,
            Integer stunnedRemainingRounds,
            Long restrainedByCharacterId,
            Boolean meleeAttackedThisRound) {
        this(cardId, actorType, participantId, name, checkValues,
                hpCurrent, hpMax, sanCurrent, sanMax, con, build, armor,
                majorWound, unconscious, dying, dead,
                temporaryInsanity, temporaryInsanityPhase,
                temporaryInsanityRemainingHours,
                inCover, coverActionForfeitPending,
                stunnedRemainingRounds, restrainedByCharacterId, null,
                meleeAttackedThisRound);
    }
}
